### ISSUE TITLE
missing location parameter in CloudBuild

### ISSUE THREAD

**Issue by jehrlich** [ingarabr/sbt-cloud-functions#1]
Thanks for this plugin. I'm using it.

I think you missed transferring the  `gcpLocation` parameter to the build command in the deploy helper, like around here  
https://github.com/ingarabr/sbt-cloud-functions/blob/edad696422158a47b7c58c6ec606096bf22d815c/modules/sbt-cloud-functions/src/main/scala/com/github/ingarabr/DeployFunctionHelper.scala#L31 a line should be inserted like ` "--region" -> config.gcpLocation`, if I'm not mistaken.

**Comment by ingarabr** [comment]
Thank you for using it :-) 

It looks like you're right that I've missed the region parameter. Do you mind creating a pull request on it?

https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--region

**Comment by ingarabr** [comment]
Awesome. I'll release it later today.
